project:
  type: book

book:
  title: "Statistics Cookbook"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/stats-cookbook
  site-url: https://stats-cookbook-lightbridge.netlify.app
  chapters:
    - index.qmd
    - references.qmd
    - part: "Linear Reg"
      chapters: 
        - "content/lm-r.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo


freeze: auto
